name: CI/CD to GKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: bhd-poker-api
  TAG_NAME: latest
  PROJECT_ID: bhd-vpoker
  DEPLOYMENT_NAME: bhd-vpoker
  CONTAINER_NAME: bhd-poker-api-sha256-1
  NAMESPACE_NAME: default
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      id: build_and_push_docker
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "::set-output name=tag_name::$TAG_NAME"
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NAME .
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NAME
        
    - name: Get GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name:  autopilot-cluster-1 
        location: us-central1
        
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG_NAME --namespace=$NAMESPACE_NAME
      env:
        TAG_NAME: ${{ steps.build_and_push_docker.outputs.tag_name }}
